import "./styles/tokens.css";
import "./widgets/clock";
import "./widgets/text";
import "./widgets/image";
import "./widgets/iframe";
import "./widgets/metric";
import "./widgets/number_with_delta";
import "./widgets/meter";
import "./widgets/list";
import "./widgets/status_grid";
import "./widgets/comments";
import "./widgets/table";
import "./widgets/line_chart";
import "./widgets/bar_chart";
import "./widgets/pie_chart";
import "./widgets/pass_rate";
import "./widgets/test_timeline";
import "./widgets/test_list";
import "./widgets/suite_progress";

export const TILER_WIDGETS_VERSION = "0.0.1" as const;
export { chartColors } from "./lib/chart-colors";
export { ClockConfig, ClockWidget } from "./widgets/clock";
export { TextConfig, TextWidget } from "./widgets/text";
export { ImageConfig, ImageWidget } from "./widgets/image";
export { IframeConfig, IframeWidget } from "./widgets/iframe";
export { MetricConfig, MetricWidget } from "./widgets/metric";
export { NumberWithDeltaConfig, NumberWithDeltaWidget } from "./widgets/number_with_delta";
export { MeterConfig, MeterWidget } from "./widgets/meter";
export { ListConfig, ListWidget } from "./widgets/list";
export { StatusGridConfig, StatusGridWidget } from "./widgets/status_grid";
export { CommentsConfig, CommentsWidget } from "./widgets/comments";
export { TableConfig, TableWidget } from "./widgets/table";
export { LineChartConfig, LineChartWidget } from "./widgets/line_chart";
export { BarChartConfig, BarChartWidget } from "./widgets/bar_chart";
export { PieChartConfig, PieChartWidget } from "./widgets/pie_chart";
export { PassRateConfig, PassRateWidget } from "./widgets/pass_rate";
export { TestTimelineConfig, TestTimelineWidget } from "./widgets/test_timeline";
export { TestListConfig, TestListWidget } from "./widgets/test_list";
export { SuiteProgressConfig, SuiteProgressWidget } from "./widgets/suite_progress";
